return {}
-- return {
--   'ray-x/lsp_signature.nvim',
--   event = 'InsertEnter',
--   opts = {
--     max_width = 40,
--     max_height = 8,
--     doc_lines = 8,
--     hint_prefix = 'λ ',
--     hint_enable = false,
--     toggle_key = '<C-h>',
--   },
--   config = function(_, opts)
--     require('lsp_signature').setup(opts)
--   end,
-- }
